2025-05-25T19:40:42.749907Z [warning  ] Force option is enabled, ignoring stale job check.
2025-05-25T19:40:42.843821Z [info     ] Using systemdb state backend
2025-05-25T19:40:42.844679Z [warning  ] No state was found, complete import.
2025-05-25T19:40:43.037739Z [error    ] Cannot start plugin tap-salesforce: Catalog discovery failed: command ['/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/bin/tap-salesforce', '--config', '/Users/tim.prudames/analytics/.meltano/run/tap-salesforce/tap.bec6684a-2655-4794-9597-9a30d51bdef4.config.json', '--discover'] returned 1 with stderr:
 /Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
CRITICAL Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/bin/tap-salesforce", line 8, in <module>
    sys.exit(main())
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 557, in main
    raise e
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 548, in main
    main_impl()
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 507, in main_impl
    args = singer_utils.parse_args(REQUIRED_CONFIG_KEYS)
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/singer/utils.py", line 183, in parse_args
    args.properties = load_json(args.properties)
  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/singer/utils.py", line 109, in load_json
    return json.load(fil)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2025-05-25T19:40:43.037888Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Cannot start plugin tap-salesforce: Catalog discovery failed: command [\'/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/bin/tap-salesforce\', \'--config\', \'/Users/tim.prudames/analytics/.meltano/run/tap-salesforce/tap.bec6684a-2655-4794-9597-9a30d51bdef4.config.json\', \'--discover\'] returned 1 with stderr:\n /Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the \'ssl\' module is compiled with \'LibreSSL 2.8.3\'. See: https://github.com/urllib3/urllib3/issues/3020\n  warnings.warn(\nCRITICAL Expecting value: line 1 column 1 (char 0)\nTraceback (most recent call last):\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/bin/tap-salesforce", line 8, in <module>\n    sys.exit(main())\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 557, in main\n    raise e\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 548, in main\n    main_impl()\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/tap_salesforce/__init__.py", line 507, in main_impl\n    args = singer_utils.parse_args(REQUIRED_CONFIG_KEYS)\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/singer/utils.py", line 183, in parse_args\n    args.properties = load_json(args.properties)\n  File "/Users/tim.prudames/analytics/.meltano/extractors/tap-salesforce/venv/lib/python3.9/site-packages/singer/utils.py", line 109, in load_json\n    return json.load(fil)\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load\n    return loads(fp.read(),\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n') exit_codes={} set_number=0 success=False
